### ISSUE TITLE
License of pp_iter.h

### ISSUE THREAD

**Issue by MarcFinetRtone** [cormacc/va_args_iterators#1]
Hello,

Thanks for great `pp_iter.h`. I was looking for full pre-processor power and finally found something that almost give access to it.

The LICENSE file mentions that code is 'gpl-v3', which is great for the generating part. However, is it the same for generated `pp_iter.h` ? I would be nice if the generated code could be reused in a more permissive way (e.g. MIT or even LGPL since it could be seen as a library, albeit w/o real code).

What do you think ?

Thanks,

Marc.

**Comment by cormacc** [comment]
Hi Marc,

Happy to switch this to MIT -- builds on ideas from a number of sources mentioned in the readme anyway. Didn't really give the license a whole lot of thought when throwing this up on github originally.

Did some more work on the fully recursive implementation a few months back, then got bogged down in trying to make it MSVC compatible (as part of a contribution to the fake function framework) and gave up in disgust :) Will see if some of that's salvageable and push an update. Probably not before next week though, as have a release looming at work.

**Comment by MarcFinetRtone** [comment]
Hello Cormac,

Thanks for considering the change. I'll then will start to use `pp_iter.h` in our internal tools, and refer this issue until the license change is effective.

Marc.

**Comment by cormacc** [comment]
@MarcFinetRtone Amended the license to MIT on master.
Out of interest -- what's your application, and do you care about MSVC compatibility? Prefer the recursive implementation for a number of reasons, but the MSVC preprocessor isn't standards compliant and can't handle it. I hope never to have to use MSVC myself (primarily embedded/gcc work I do), so not particularly motivated to support it, having wasted a couple of days banging my head against the problem a year or so back.
MS were threatening to produce a more compliant preprocessor, but haven't seen anything more since this 2018 blog post.
https://devblogs.microsoft.com/cppblog/msvc-preprocessor-progress-towards-conformance/

**Comment by MarcFinetRtone** [comment]
> @MarcFinetRtone Amended the license to MIT on master.
> Out of interest -- what's your application, and do you care about MSVC compatibility?

I dont care about MSVC compatibility; I'm using gcc and am in embedded world too  :wink:

Thanks for the licence change.

**Comment by cormacc** [comment]
No bother. Reckon I'll ditch the MSVC compatibility stuff from master if/when I next get a couple of days to get my head back in this (preprocessor stuff takes me a bit of re-adjustment after a hiatus -- hard to dip in). Park it in a branch -- if anyone cares, they can pick it up. The rest of it will be easier to parse/maintain without it.
